---
name: James Hogg
#surname: Hogg
position: "PhD Student"
address: "School of Mathematical Sciences, Queensland University of Technology"
profilepic: "C:/r_proj/cv_rmarkdown/img/IMG_0667-min.jpg"
#phone:
email: "james.hogg@hdr.qut.edu.au"
twitter: JamieAHogg
github: JamieHogg-depo
linkedin: jamieahogg
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "I am a current PhD student in the School of Mathematical Sciences at the Queensland University of Technology (QUT) under the supervision of Distinguished Professor Kerrie Mengersen, Dr Susanna Cramb, Professor Peter Baade and Dr Jessica Cameron. My PhD work is funded by the internationally-awarded Australian Cancer Atlas, where my role is to develop Bayesian methodology to generate small area level cancer risk factor estimates. I am passionate about accessible research, Bayesian inference, and spatial modelling, and am dedicated to making a positive impact in the field of cancer research."
headcolor: 414141
output:
  vitae::awesomecv:
  page_total: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(readxl)

readExcelSheets <- function(filename){
  # read all sheets in .xlsx 
  all <- readxl::excel_sheets(filename)
  # import each sheet into a list using readxl::read_excel
  list <- lapply(all, function(x) readxl::read_excel(filename, sheet = x))
  # save sheet name for each sheet (list)
  names(list) <- all
  # breaks up list and creates a dataframe for each sheet with df names matching sheet names
  list2env(list, envir = .GlobalEnv)
}

readExcelSheets("C:/r_proj/cv_rmarkdown/JH_data.xlsx")
```

# Research interests

```{r}
interests %>% 
  brief_entries(what = points) 
```

# Education and qualifications

```{r}
education %>% 
  detailed_entries(with = degree, # this is bold 
                   when = year, 
                   what = institution, 
                   where = where,
                   why = details) # dot points
```

# Experience 

```{r}
# tibble::tribble(
#   ~what,
#   "Course title: Categorical Data and Generalised Linear Models (STAT7608)
# "
# ) %>%
#   detailed_entries(
#     what = what,
#     .protect = FALSE
#   )

experience %>%
  detailed_entries(with = role, # this is bold
                   when = dates,
                   what = institution,
                   where = where,
                   why = details, # dot points
                   .protect = T)
```

# Selected research presentations

```{r}
presentations %>% 
  # select some talks
  slice(-c(1,2,11)) %>% 
  # add title to each
  mutate(title = paste0("Title: ", title)) %>% 
  detailed_entries(with = what, # this is bold 
                   when = date, 
                   what = conference, 
                   where = where,
                   why = title) # dot points
```

# Awards

```{r}
awards %>% 
  detailed_entries(with = award, # this is bold 
                   when = when, 
                   what = conference_event) 
```

# Professional memberships

```{r}
membership %>% 
  brief_entries(what = notes) 
```

# Software

```{r}
software %>% 
  brief_entries(what = notes) 
```

# Referees

```{r}
referees %>% 
  detailed_entries(with = name, # this is bold 
                   where = institution,
                   what = position, 
                   why = details)
```

<!-- # Publications -->

<!-- ```{r} -->
<!-- library(dplyr) -->
<!-- knitr::write_bib(c("vitae", "tibble"), "packages.bib") -->

<!-- bibliography_entries("packages.bib") %>% -->
<!--   arrange(desc(author$family), issued) -->
<!-- ``` -->

