---
name: James Hogg
#surname: Hogg
position: "PhD Student"
address: "School of Mathematical Sciences, Queensland University of Technology"
# profilepic: "C:/r_proj/cv_rmarkdown/img/IMG_0667-min.jpg"
# profilepic: "C:/r_proj/cv_rmarkdown/img/profile2.jpg"
#phone:
email: "james.hogg@hdr.qut.edu.au"
twitter: JamieAHogg
github: JamieHogg-depo
linkedin: jamieahogg
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "I am a statistician currently studying for a PhD in the School of Mathematical Sciences at the Queensland University of Technology (QUT). Focused on generating small area level estimates of cancer risk factors for the globally recognized Australian Cancer Atlas, my research is driven by a passion for making research more accessible, as well as a commitment to utilizing Bayesian inference and spatial modeling to enhance the field of cancer research. My teaching experience, together with the awards I've received for presentations and invited talks, attest to my proficiency in conveying complex statistical ideas to a wide audience. With my dedication to advancing the field of cancer research and a deep-seated enthusiasm for exploring the potential of Bayesian inference and spatial modeling, I am poised to make a significant contribution to either academic or industry roles."
headcolor: 414141
output:
  vitae::awesomecv:
  page_total: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(readxl)

readExcelSheets <- function(filename){
  # read all sheets in .xlsx 
  all <- readxl::excel_sheets(filename)
  # import each sheet into a list using readxl::read_excel
  list <- lapply(all, function(x) readxl::read_excel(filename, sheet = x))
  # save sheet name for each sheet (list)
  names(list) <- all
  # breaks up list and creates a dataframe for each sheet with df names matching sheet names
  list2env(list, envir = .GlobalEnv)
}

readExcelSheets("C:/r_proj/cv_rmarkdown/JH_data.xlsx")
```

<!-- # Research interests -->

<!-- ```{r} -->
<!-- interests %>% -->
<!--   brief_entries(what = points) -->
<!-- ``` -->

# Employment 

```{r}
employment %>%
  detailed_entries(with = role, # this is bold
                   when = dates,
                   what = institution,
                   where = where,
                   why = details, # dot points
                   .protect = T)
```

# Education and qualifications

```{r}
education %>% 
  detailed_entries(with = degree, # this is bold 
                   when = year, 
                   what = institution, 
                   where = where,
                   why = details) # dot points
```

# Professional service 

```{r}
professional_service %>%
  detailed_entries(with = role, # this is bold
                   when = dates,
                   what = institution,
                   where = where,
                   why = details, # dot points
                   .protect = T)
```

# Selected research presentations

```{r}
presentations %>% 
  # select some talks
  filter(include == 1) %>% 
  # add title to each
  mutate(title = paste0("Title: ", title)) %>% 
  detailed_entries(with = what, # this is bold 
                   when = date, 
                   what = conference, 
                   where = where,
                   why = title) # dot points
```

# Selected publications

```{r}
papers %>% 
  # select some talks
  filter(include == 1) %>% 
  mutate(authors = paste0("\\", authors),
         journal_year = paste0("\\", journal_year)) %>% 
  detailed_entries(with = journal_year, # this is bold 
                   what = authors,
                   why = title, .protect = FALSE) 
```

# Awards

```{r}
awards %>% 
  detailed_entries(with = award, # this is bold 
                   when = when, 
                   what = conference_event,
                   why = details) 
```

# Professional memberships

```{r}
membership %>%
  brief_entries(what = notes)
```

# Software

```{r}
software %>%
  brief_entries(what = paste0(what, ": ", notes))
```

<!-- # Referees -->

<!-- ```{r} -->
<!-- referees %>% -->
<!--   detailed_entries(with = name, # this is bold -->
<!--                    where = institution, -->
<!--                    what = position, -->
<!--                    why = details) -->
<!-- ``` -->

<!-- # Publications -->

<!-- ```{r} -->
<!-- library(dplyr) -->
<!-- knitr::write_bib(c("vitae", "tibble"), "packages.bib") -->

<!-- bibliography_entries("packages.bib") %>% -->
<!--   arrange(desc(author$family), issued) -->
<!-- ``` -->

